### PR TITLE
Test cluster chart PR #348

### PR DESCRIPTION
**Pull request by taylorbot**
> [!WARNING]
> DO NOT MERGE! This PR has been created automatically by @taylorbot on behalf of Jose Armesto (@fiunchinho).

### Changes

Update the cluster chart version from `1.4.1` to `1.4.1-49f77ba5fdd77a752569c38e53b0960d7d6d99e0` in order to test @fiunchinho's cluster chart pull request https://github.com/giantswarm/cluster/pull/348.

Cluster chart pull request title: `Allow to configure cgroupsv1 per nodepool`.

### Testing

Please comment this pull request with `/run cluster-test-suites` in order to run e2e tests.

### CODE REVIEW

**Comment by AverageMarcus** [comment]
Sorry for the noise but I need to trigger this specific PR to debug why we're getting leftover resources.

/run cluster-test-suites TARGET_SUITES=./providers/capa/upgrade

**Comment by AverageMarcus** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capa/upgrade

**Comment by ljakimczuk** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capa/upgrade

**Comment by Gacko** [comment]
I removed the old trigger and result comments for readability.

**Pull request closed without merging**
