### PR TITLE
Render MachineHealthCheck from cluster chart

### PR DESCRIPTION
**Pull request by nprokopic**
Closes https://github.com/giantswarm/roadmap/issues/3047

### What this PR does / why we need it

This PR removes MachineHealthCheck from cluster-aws and it configures cluster chart to render it.

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by nprokopic** [comment]
>     /metadata  (MachineHealthCheck/org-giantswarm/test-wc-minimal-control-plane)
>       + one map entry added:
>         annotations:

Will fix this to remove the empty map.

**Review by weseven — APPROVED** [review]

**Comment by nprokopic** [comment]
One more check after updating the PR

/run cluster-test-suites

**Review by calvix — APPROVED** [review]
lgtm if the rendered health check is the same as before

**Comment by nprokopic** [comment]
> lgtm if the rendered health check is the same as before

With the few expected labels/annotations being different (e.g. team name, chart name), the rendered MachineHealthCheck resource is the same (the MachineHealthCheck  template code in cluster chart is basically copy-pasted from cluster-aws).

**Comment by nprokopic** [comment]
I have rebased the PR to resolve git conflicts in CHANGELOG.

**Review by calvix — APPROVED** [review]

**Comment by nprokopic** [comment]
autoscaler e2e tests not be affected by this PR, retrying one more time

/run cluster-test-suites

**Comment by nprokopic** [comment]
Another attempt after merging the fix here https://github.com/giantswarm/cluster-aws/pull/508

/run cluster-test-suites

**Pull request merged**
