### PR TITLE
Toggle audit

### PR DESCRIPTION
**Pull request by njuettner**
Towards: https://github.com/giantswarm/roadmap/issues/3669

### Checklist

- [x] Updated CHANGELOG.md.

### Trigger E2E tests

/run cluster-test-suites

### CODE REVIEW

**Comment by njuettner** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capa/china,./providers/capa/cilium-eni-mode

**Comment by njuettner** [comment]
Creating cluster in China failing due to:

```
  [FAILED] in [It] - /app/internal/common/hello.go:164 @ 09/06/24 13:22:04.928
• [FAILED] [361.515 seconds]
Common tests hello world [It] should deploy the hello-world app
/app/internal/common/hello.go:113

  [FAILED] Timed out after 360.001s.
  Expected
      <bool>: false
  to be true
  In [It] at: /app/internal/common/hello.go:164 @ 09/06/24 13:22:04.928
```

Don't think that is related with my change.

**Review by AverageMarcus — APPROVED** [review]

**Review by Gacko — APPROVED** [review]

**Comment by Gacko** [comment]
I feel like something's wrong with `grizzly` now.

**Comment by Gacko** [comment]
... while on the other hand App Test Suites for `ingress-nginx-app` are working. So give it another try.

/run cluster-test-suites

🙏

**Comment by njuettner** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capa/standard,./providers/capa/cilium-eni-mode

**Comment by njuettner** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capa/cilium-eni-mode

**Pull request merged**
