### PR TITLE
Disallow additionalProperties on nodePools (breaking)

### PR DESCRIPTION
**Pull request by marians**
### What this PR does / why we need it

Closes https://github.com/giantswarm/roadmap/issues/2581 . See issue for details.

**NOTE**: This is a **breaking change** where node pool names are in use that do not match the pattern `^[a-z0-9]{5,10}$`.

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/test create
/test upgrade
/run cluster-test-suites

### CODE REVIEW

**Review by fiunchinho — APPROVED** [review]

**Comment by marians** [comment]
@fiunchinho Thanks, however currently I'm not allowed yet. Looks like the upgrade check is still required and also Heimdall says: 

image

**Comment by marians** [comment]
> you can ignore that and use your admin permissions to merge it.

Thanks, now I get it

**Pull request merged**
