### PR TITLE
Test cluster chart PR #275

### PR DESCRIPTION
**Pull request by taylorbot**
> [!WARNING]
> DO NOT MERGE! This PR has been created automatically by @taylorbot on behalf of Jose Armesto (@fiunchinho).

### Changes

Update the cluster chart version from `0.36.0` to `1.0.0-ede14beed0f11321487a8947fafb0a10fc509cef` in order to test @fiunchinho's cluster chart pull request https://github.com/giantswarm/cluster/pull/275.

Cluster chart pull request title: `Use helper to render labels`.

### Testing

Please comment this pull request with `/run cluster-test-suites` in order to run e2e tests.

### CODE REVIEW

**Comment by AndiDog** [comment]
Hmm, unrelated error?

```
global.components.containerd: Additional property managementClusterRegistryCache is not allowed
```

**Comment by Gacko** [comment]
This PR here bases on a `cluster-aws` version that still uses `cluster` v0.36.0 while your `cluster` PR bases on `cluster` v1.0.0.

@nprokopic is currently about to bump the `cluster` chart to v1.0.0 in this PR: https://github.com/giantswarm/cluster-aws/pull/718

So either you rebase this PR on his and re-run the tests... or you ignore it.

**Comment by nprokopic** [comment]
> This PR here bases on a cluster-aws version that still uses cluster v0.36.0 while your cluster PR bases on cluster v1.0.0.

Yeah, bad timing :see_no_evil: I think this will cause your tests to fail here, as cluster chart v1.0.0 required few JSON schema changes in cluster-aws.

After rebasing here it should work.

**Comment by Gacko** [comment]
I merged `main` into this PR.

**Pull request closed without merging**
