### PR TITLE
Allow scraping of targets

### PR DESCRIPTION
**Pull request by QuentinBisson**
### What this PR does / why we need it

Towards https://github.com/giantswarm/giantswarm/issues/24059 and https://github.com/giantswarm/giantswarm/issues/24456

How can we release that once merged?

cc @marieroque for the etcd issue

### Checklist

- [ ] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/test create
/test upgrade

### CODE REVIEW

**Comment by QuentinBisson** [comment]
also @giantswarm/team-hydra how do I know why the tests are failing ;D

**Comment by fiunchinho** [comment]
Sorry, tests don't work at the moment on CAPA.

**Review by fiunchinho — APPROVED** [review]

**Comment by QuentinBisson** [comment]
Can I force merge? And will it be deployed everywhere if I release?

**Comment by AverageMarcus** [comment]
@QuentinBisson have you manually tested creating a WC with this yet?

Merging won't auto-deploy anywhere but all new WCs created will use it.

The management-clusters-fleet repo will need updating to upgrade the MCs when this is released.

**Comment by marieroque** [comment]
Tests are ok on `golem`:
`etcd`, `controller-manager` and `scheduler` targets are now correctly scraped.

**Pull request merged**
