### PR TITLE
remove-cluster-role-identity-from-repo

### PR DESCRIPTION
**Pull request by calvix**
It does not seem to be a very good idea to have AWSClusterRole as part of this app, as deletion of it will cause cluster stuck in deletion

instead, we will create a default role with capa controller app

### CODE REVIEW

**Comment by AverageMarcus** [comment]
How about leveraging Helm pre/post hooks to handle the creation and deletion of this resource?

**Comment by calvix** [comment]
> How about leveraging Helm pre/post hooks to handle the creation and deletion of this resource?

How would that help?

**Comment by AverageMarcus** [comment]
Ensures the `AWSClusterRole` isn't removed until the cluster is.

**Comment by calvix** [comment]
> Ensures the `AWSClusterRole` isn't removed until the cluster is.

In the end, I think having a unique `AWSClusterRole` for every cluster is not such a good idea, and rather have a similar way how we to credentials now, it's only one unique ARN role, and than you reference that role in the CR via name. using `default` as default

It also simplifies the required arguments you need in order to generate yamls for a cluster.

**Comment by AverageMarcus** [comment]
Makes sense. 👍

**Review by AverageMarcus — APPROVED** [review]

**Pull request merged**
