### PR TITLE
bump kubernetes version to 1.25.16

### PR DESCRIPTION
**Pull request by mnitchev**
### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Review by T-Kukawka — APPROVED** [review]

**Comment by mnitchev** [comment]
forgot to release the default apps :facepalm:

**Comment by mnitchev** [comment]
hmm looks like there's some invalid manifests actually. I'll check that on Monday

**Pull request merged**
