### PR TITLE
Chart: Bump `cluster` chart v0.18.0.

### PR DESCRIPTION
**Pull request by tuladhar**
### What this PR does / why we need it
- Bumps the cluster chart https://github.com/giantswarm/cluster/pull/141

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by Gacko** [comment]
https://github.com/giantswarm/cluster

**Review by Gacko — APPROVED** [review]

**Comment by nprokopic** [comment]
@tuladhar @Gacko I have rebased this PR so it now upgrades cluster chart from v0.17.0 to v0.18.0.

When upgrading from v0.16.0 to v0.18.0 the e2e tests were failing, and now since v0.17.0 e2e tests were green, it seems that changes from v0.18.0 are breaking the e2e tests, but will run them now again, so we see how it goes.

/run cluster-test-suites

**Comment by nprokopic** [comment]
Before rebasing the error was about aws-pod-identity-webhook-app not having replicas:

```
{"level":"info","ts":"2024-04-11T09:57:15Z","msg":"deployment kube-system/aws-pod-identity-webhook-app has 0/3 replicas available"}
  {"level":"info","ts":"2024-04-11T09:57:26Z","msg":"deployment kube-system/aws-pod-identity-webhook-app has 0/3 replicas available"}
  [FAILED] in [It] - /app/internal/common/basic.go:78 @ 04/11/24 09:57:32.915
• [FAILED] [900.001 seconds]
Basic upgrade test basic [It] has all its Deployments Ready (means all replicas are running)
/app/internal/common/basic.go:74

  [FAILED] Timed out after 900.000s.
  Expected success, but got an error:
      <*errors.errorString | 0xc000ab0910>: 
      deployment kube-system/aws-pod-identity-webhook-app has 0/3 replicas available
      {
          s: "deployment kube-system/aws-pod-identity-webhook-app has 0/3 replicas available",
      }
  In [It] at: /app/internal/common/basic.go:78 @ 04/11/24 09:57:32.915
```

Now it's another failure with hello-world replicas:

```
Basic upgrade test scale scales node by creating anti-affiniy pods
/app/internal/common/scale.go:87
  {"level":"info","ts":"2024-04-11T14:24:47Z","msg":"Checking if App status for t-0eo53a5tf1up53vnu2-scale-hello-world is equal to 'deployed': "}
  {"level":"info","ts":"2024-04-11T14:24:52Z","msg":"Checking if App status for t-0eo53a5tf1up53vnu2-scale-hello-world is equal to 'deployed': deployed"}
  {"level":"info","ts":"2024-04-11T14:24:52Z","msg":"Checking for increased replicas. Expected: 6, Actual: 3"}

  >>>truncated<<<

  {"level":"info","ts":"2024-04-11T14:38:16Z","msg":"Checking for increased replicas. Expected: 6, Actual: 3"}
  {"level":"info","ts":"2024-04-11T14:38:26Z","msg":"Checking for increased replicas. Expected: 6, Actual: 3"}
  {"level":"info","ts":"2024-04-11T14:38:36Z","msg":"Checking for increased replicas. Expected: 6, Actual: 3"}
  {"level":"info","ts":"2024-04-11T14:38:46Z","msg":"Checking for increased replicas. Expected: 6, Actual: 3"}
  {"level":"info","ts":"2024-04-11T14:38:56Z","msg":"Checking for increased replicas. Expected: 6, Actual: 3"}
  {"level":"info","ts":"2024-04-11T14:39:06Z","msg":"Checking for increased replicas. Expected: 6, Actual: 4"}
  {"level":"info","ts":"2024-04-11T14:39:16Z","msg":"Checking for increased replicas. Expected: 6, Actual: 5"}
  {"level":"info","ts":"2024-04-11T14:39:26Z","msg":"Checking for increased replicas. Expected: 6, Actual: 5"}
  {"level":"info","ts":"2024-04-11T14:39:36Z","msg":"Checking for increased replicas. Expected: 6, Actual: 5"}
  {"level":"info","ts":"2024-04-11T14:39:46Z","msg":"Checking for increased replicas. Expected: 6, Actual: 5"}
  [FAILED] in [It] - /app/internal/common/scale.go:112 @ 04/11/24 14:39:52.746
• [FAILED] [906.442 seconds]
Basic upgrade test scale [It] scales node by creating anti-affiniy pods
/app/internal/common/scale.go:87

  [FAILED] Timed out after 900.000s.
  Expected
      <string>: 5
  to equal
      <string>: 6
  In [It] at: /app/internal/common/scale.go:112 @ 04/11/24 14:39:52.746
```

**Comment by nprokopic** [comment]
Another try, if it fails differently again, something is flaky 

/run cluster-test-suites

**Comment by nprokopic** [comment]
The upgrade was supposedly successful

```
Basic upgrade test upgrade should upgrade successfully
/app/internal/upgrade/upgrade.go:64
  {"level":"info","ts":"2024-04-12T08:25:20Z","msg":"Checking for valid Kubeconfig for cluster t-crwke2vvlr612p159w"}
  {"level":"info","ts":"2024-04-12T08:25:20Z","msg":"Got valid kubeconfig!"}
  {"level":"info","ts":"2024-04-12T08:25:20Z","msg":"Namespace default exists"}
  {"level":"info","ts":"2024-04-12T08:25:20Z","msg":"Checking if App version for t-crwke2vvlr612p159w-default-apps is equal to 'v0.50.0': 0.50.0"}
  {"level":"info","ts":"2024-04-12T08:25:20Z","msg":"Checking if App status for t-crwke2vvlr612p159w-default-apps is equal to 'deployed': deployed"}
  {"level":"info","ts":"2024-04-12T08:25:20Z","msg":"Checking if App version for t-crwke2vvlr612p159w is equal to 'v0.69.0-013fc0816f04c3036089c30c1e288e67cdbbf17d': 0.69.0"}
  {"level":"info","ts":"2024-04-12T08:25:25Z","msg":"Checking if App version for t-crwke2vvlr612p159w is equal to 'v0.69.0-013fc0816f04c3036089c30c1e288e67cdbbf17d': 0.69.0"}
  {"level":"info","ts":"2024-04-12T08:25:30Z","msg":"Checking if App version for t-crwke2vvlr612p159w is equal to 'v0.69.0-013fc0816f04c3036089c30c1e288e67cdbbf17d': 0.69.0"}
  {"level":"info","ts":"2024-04-12T08:25:35Z","msg":"Checking if App version for t-crwke2vvlr612p159w is equal to 'v0.69.0-013fc0816f04c3036089c30c1e288e67cdbbf17d': 0.69.0-013fc0816f04c3036089c30c1e288e67cdbbf17d"}
  {"level":"info","ts":"2024-04-12T08:25:36Z","msg":"Checking if App status for t-crwke2vvlr612p159w is equal to 'deployed': deployed"}
• [17.025 seconds]
```

but the current state of nodes is:

```
kubectl get nodes
NAME                                         STATUS                        ROLES                  AGE     VERSION
ip-10-0-103-179.eu-west-2.compute.internal   Ready                         control-plane,master   13m     v1.25.16
ip-10-0-147-7.eu-west-2.compute.internal     Ready                         control-plane,master   105s    v1.25.16
ip-10-0-162-93.eu-west-2.compute.internal    NotReady,SchedulingDisabled   control-plane,master   10m     v1.25.16
ip-10-0-167-21.eu-west-2.compute.internal    Ready                         worker                 12m     v1.25.16
ip-10-0-253-78.eu-west-2.compute.internal    Ready                         control-plane,master   4m25s   v1.25.16
ip-10-0-67-160.eu-west-2.compute.internal    Ready                         worker                 4m30s   v1.25.16
```

**Review by AndiDog — APPROVED** [review]
We should state that this will roll all worker nodes.

**Pull request merged**
