### PR TITLE
enable-private-bastion

### PR DESCRIPTION
**Pull request by calvix**
subnet filter tags need to be changed in case of private cluster

tested on goat

### CODE REVIEW

**Review by mnitchev — APPROVED** [review]

**Comment by mnitchev** [comment]
Looks like that doesn't render though

**Comment by calvix** [comment]
> Looks like that doesn't render though

should be fixed

**Comment by mnitchev** [comment]
Hmm looks like the tests don't trigger either for some reason.
/test create
/test upgrade

**Pull request merged**
