### PR TITLE
fix IRSA placeholder replacer

### PR DESCRIPTION
**Pull request by bdehri**
### What this PR does / why we need it

At the moment, CAPA cluster upgrades require manuel intervention due to service-account-issuer placeholder is not replaced on non-init nodes. This PR enables replacing of the placeholder on non-init nodes.

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/test create
/test upgrade

### CODE REVIEW

**Review by AverageMarcus — APPROVED** [review]
Can I assume that only replacing in the api-server manifest works for both init and join then?

If so, LGTM :)

**Comment by bdehri** [comment]
> Can I assume that only replacing in the api-server manifest works for both init and join then?
> 
> If so, LGTM :)

Yes

**Review by fiunchinho — APPROVED** [review]

**Pull request merged**
