### PR TITLE
Render MachinePools from cluster chart

### PR DESCRIPTION
**Pull request by nprokopic**
Closes https://github.com/giantswarm/roadmap/issues/3194

### What this PR does / why we need it

This PR update cluster-aws to render MachinePool and KubeadmConfig resources from the cluster chart.

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by nprokopic** [comment]
Test after fixing node directories for node pools.

/run cluster-test-suites

**Comment by nprokopic** [comment]
After fixing few issues from cluster chart:

❌ CAPA Private Suite
✅ CAPA Standard Suite
✅ CAPA Upgrade Suite

Looks promising! 😬 

Re-running once again, to see if private suite is flaky.

/run cluster-test-suites

**Comment by nprokopic** [comment]
Latest run results after bumping cluster chart to a released version (without any functional changes compared to the previous test version):

✅ CAPA Private Suites passed

❌ CAPA Standard Suites failed (known flaky test)

```
Common tests scale [It] scales node by creating anti-affiniy pods
/app/internal/common/scale.go:87

  [FAILED] Timed out after 900.000s.
  Expected
      <string>: 2
  to equal
      <string>: 4
  In [It] at: /app/internal/common/scale.go:112 @ 02/09/24 12:43:21.2
```

❌ CAPA Upgrade Suite failed (this looks like some transient issue)

```
Basic upgrade test basic [It] has all of its Pods in the Running state
/app/internal/common/basic.go:73

  [FAILED] Timed out after 900.002s.
  Expected success, but got an error:
      <*errors.errorString | 0xc0002b1a30>: 
      pod kube-system/promtail-jswd8 in Pending phase
      {
          s: "pod kube-system/promtail-jswd8 in Pending phase",
      }
  In [It] at: /app/internal/common/basic.go:77 @ 02/09/24 12:29:24.155
```

**Comment by nprokopic** [comment]
Here are human-readable side by side diffs of old (left) and new (right) KubeadmConfig after modifying YAML a bit (converting arrays into maps), so that comparison is actually readable:

### Metadata

Expected diff in labels and annotations, and expectedly CR has new name since hash of the spec is appended (spec is different, see below):

image

### Files

Expected one new file for audit-rules (because new release includes [this cluster PR](https://github.com/giantswarm/cluster/pull/73)):

image

Added recommended TLS cipher suites in kubelet configuration file:

image

### systemd units

Removed `kubereserved.slice` from systemd units, as it was incorrectly written anyway:

image

### Other

Non-functional newlines and empty objects diff:

image

**Comment by nprokopic** [comment]
KubeadmControlPlane diff (part that is not well-readable in GitHub action) that we have here as new cluster chart v0.8.0 also includes few changes for control plane:

### systemd units

Added another environment file to kubeadm systemd unit. New file is for for API server fairness config, 

image

systemd units for setting up above-mentioned API server environment file and etcd defrag (implemented [here](https://github.com/giantswarm/cluster/pull/74) and part of the new release that is used here):

image

In the GitHub action output for Helm rendering diff you can find `/opt/bin/setup-apiserver-environment.sh` being added to the list of files.

**Comment by nprokopic** [comment]
Retrying after this got merged and released (max nodes increased from 3 to 5) https://github.com/giantswarm/cluster-test-suites/pull/216

/run cluster-test-suites

**Review by calvix — APPROVED** [review]

**Comment by AverageMarcus** [comment]
The CAPA tests have been green the last 4 days so going to see if these now pass (and in the process test that the new clusters are correctly getting GitHub webhooks 😉 )

/run cluster-test-suites

**Review by AverageMarcus — CHANGES_REQUESTED** [review]
Upgrades are broken with these changes.

```
  Warning  ControlPlaneUnhealthy  19m                   kubeadm-control-plane-controller  Waiting for control plane to pass preflight checks to continue reconciliation: [machine t-id6y4pxrrllrxe25zc-2xg7v reports ControllerManagerPodHealthy condition is false (Info, Waiting for startup or readiness probes), machine t-id6y4pxrrllrxe25zc-2xg7v reports SchedulerPodHealthy condition is false (Info, Waiting for startup or readiness probes)]
  Warning  ControlPlaneUnhealthy  14m (x2 over 14m)     kubeadm-control-plane-controller  (combined from similar events): Waiting for control plane to pass preflight checks to continue reconciliation: [machine t-id6y4pxrrllrxe25zc-wmxdn reports APIServerPodHealthy condition is false (Error, Missing node), machine t-id6y4pxrrllrxe25zc-wmxdn reports ControllerManagerPodHealthy condition is false (Error, Missing node), machine t-id6y4pxrrllrxe25zc-wmxdn reports SchedulerPodHealthy condition is false (Error, Missing node), machine t-id6y4pxrrllrxe25zc-wmxdn reports EtcdPodHealthy condition is false (Error, Missing node)]
  Warning  ControlPlaneUnhealthy  4m16s (x33 over 12m)  kubeadm-control-plane-controller  Waiting for control plane to pass preflight checks to continue reconciliation: machine t-id6y4pxrrllrxe25zc-wmxdn reports APIServerPodHealthy condition is false (Error, CrashLoopBackOff)
```

It rolls the control plane nodes but they don't come up healthy.

**Comment by nprokopic** [comment]
Runing e2e tests to debug issues and check for known API server problems.

/run cluster-test-suites

**Comment by nprokopic** [comment]
@AverageMarcus this should fix the issue we're seeing here in the PR https://github.com/giantswarm/cluster/pull/95

**Review by AverageMarcus — APPROVED** [review]
I'm happy now the tests are passing. If Phoenix are happy with the change this should be good to go.

**Comment by nprokopic** [comment]
@AverageMarcus it's actually still not fixed 😄 

> ## cluster-test-suites
> Run name	`pr-cluster-aws-504-cluster-test-suitesp4cxq`
> Commit SHA	[cf73a69](https://github.com/giantswarm/cluster-aws/commit/cf73a697da2b2bbd40c7a9d1083f58be91a512fc)
> Result	Succeeded ✅
> [📋 View full results in Tekton Dashboard](https://tekton.ci.giantswarm.io/#/namespaces/tekton-pipelines/pipelineruns/pr-cluster-aws-504-cluster-test-suitesp4cxq?pipelineTask=display-results&step=display-results)
> 
> **Rerun trigger:** `/run cluster-test-suites`

What also worries me here is that we actually saw the issue in CAPA Upgrade suite in this e2e test run that passed here.

This test passed, bit I think it should have probably failed:

```
Basic upgrade test basic has all the control-plane nodes running
/app/internal/common/basic.go:42
  {"level":"info","ts":"2024-02-21T10:52:16Z","msg":"Checking for ready nodes"}
  {"level":"info","ts":"2024-02-21T10:52:16Z","msg":"4 nodes ready, expecting 3"}
  {"level":"info","ts":"2024-02-21T10:52:21Z","msg":"Checking for ready nodes"}
  {"level":"info","ts":"2024-02-21T10:52:21Z","msg":"4 nodes ready, expecting 3"}
  {"level":"info","ts":"2024-02-21T10:52:26Z","msg":"Checking for ready nodes"}
  {"level":"info","ts":"2024-02-21T10:52:26Z","msg":"4 nodes ready, expecting 3"}
  {"level":"info","ts":"2024-02-21T10:52:31Z","msg":"Checking for ready nodes"}
  {"level":"info","ts":"2024-02-21T10:52:31Z","msg":"4 nodes ready, expecting 3"}
  {"level":"info","ts":"2024-02-21T10:52:36Z","msg":"Checking for ready nodes"}
  {"level":"info","ts":"2024-02-21T10:52:36Z","msg":"4 nodes ready, expecting 3"}
  {"level":"info","ts":"2024-02-21T10:52:41Z","msg":"Checking for ready nodes"}
  {"level":"info","ts":"2024-02-21T10:52:41Z","msg":"4 nodes ready, expecting 3"}
  {"level":"info","ts":"2024-02-21T10:52:46Z","msg":"Checking for ready nodes"}
  {"level":"info","ts":"2024-02-21T10:52:46Z","msg":"4 nodes ready, expecting 3"}
  {"level":"info","ts":"2024-02-21T10:52:51Z","msg":"Checking for ready nodes"}
  {"level":"info","ts":"2024-02-21T10:52:51Z","msg":"4 nodes ready, expecting 3"}
  {"level":"info","ts":"2024-02-21T10:52:56Z","msg":"Checking for ready nodes"}
  {"level":"info","ts":"2024-02-21T10:52:56Z","msg":"4 nodes ready, expecting 3"}
  {"level":"info","ts":"2024-02-21T10:53:01Z","msg":"Checking for ready nodes"}
  {"level":"info","ts":"2024-02-21T10:53:01Z","msg":"4 nodes ready, expecting 3"}
  {"level":"info","ts":"2024-02-21T10:53:06Z","msg":"Checking for ready nodes"}
  {"level":"info","ts":"2024-02-21T10:53:06Z","msg":"4 nodes ready, expecting 3"}
  {"level":"info","ts":"2024-02-21T10:53:11Z","msg":"Checking for ready nodes"}
  {"level":"info","ts":"2024-02-21T10:53:11Z","msg":"4 nodes ready, expecting 3"}
• [65.047 seconds]
```

Here there were 4 control plane nodes, I think 3 old ones, 1 new, and API server was crashlooping on the new node.

So I think it would be good to have a test that checks if all API server pods are up & running, maybe some improvements as a part of this https://github.com/giantswarm/roadmap/issues/3239 (I would gladly help here once I'm back from my vacation after 5th of March).

**Comment by nprokopic** [comment]
Running tests with this fix https://github.com/giantswarm/cluster/pull/95

/run cluster-test-suites

**Comment by nprokopic** [comment]
And hopefully final e2e test run with released cluster chart version

/run cluster-test-suites

**Comment by nprokopic** [comment]
In CAPA Upgrade suite the cluster upgrade finished really successfully and control plane nodes finished rolling upgrade correctly.

This is the WC state after the cluster upgrade:

```
clusterctl describe cluster -n org-t-3c4tzubm0elp5d3488 t-9z73sqxubetcjijh82 --show-conditions all --grouping=false
NAME                                                       READY  SEVERITY  REASON            SINCE  MESSAGE
Cluster/t-9z73sqxubetcjijh82                               True                               15s
│           ├─ControlPlaneInitialized                      True                               22m
│           ├─ControlPlaneReady                            True                               15s
│           ├─InfrastructureReady                          True                               23m
│           └─NetworkTopologyReady                         False  Info      ModeNotSupported  27m    The provided mode 'None' is not supported
├─ClusterInfrastructure - AWSCluster/t-9z73sqxubetcjijh82  True                               23m
│             ├─ClusterSecurityGroupsReady                 True                               25m
│             ├─InternetGatewayReady                       True                               27m
│             ├─LoadBalancerReady                          True                               23m
│             ├─NatGatewaysReady                           True                               25m
│             ├─RouteTablesReady                           True                               25m
│             ├─SubnetsReady                               True                               27m
│             └─VpcReady                                   True                               27m
├─ControlPlane - KubeadmControlPlane/t-9z73sqxubetcjijh82  True                               15s
│ │           ├─Available                                  True                               22m
│ │           ├─CertificatesAvailable                      True                               23m
│ │           ├─ControlPlaneComponentsHealthy              True                               15s
│ │           ├─EtcdClusterHealthy                         True                               15s
│ │           ├─MachinesCreated                            True                               17m
│ │           ├─MachinesReady                              True                               15s
│ │           ├─MachinesSpecUpToDate                       True                               109s
│ │           └─Resized                                    True                               19s
│ ├─Machine/t-9z73sqxubetcjijh82-bgvdv                     True                               13m
│ │             ├─APIServerPodHealthy                      True                               12m
│ │             ├─BootstrapReady                           True                               13m
│ │             ├─ControllerManagerPodHealthy              True                               11m
│ │             ├─EtcdMemberHealthy                        True                               7m24s
│ │             ├─EtcdPodHealthy                           True                               12m
│ │             ├─HealthCheckSucceeded                     True                               12m
│ │             ├─InfrastructureReady                      True                               13m
│ │             ├─NodeHealthy                              True                               12m
│ │             └─SchedulerPodHealthy                      True                               12m
│ ├─Machine/t-9z73sqxubetcjijh82-btkgg                     True                               8m28s
│ │             ├─APIServerPodHealthy                      True                               7m48s
│ │             ├─BootstrapReady                           True                               9m2s
│ │             ├─ControllerManagerPodHealthy              True                               7m48s
│ │             ├─EtcdMemberHealthy                        True                               8m4s
│ │             ├─EtcdPodHealthy                           True                               8m
│ │             ├─HealthCheckSucceeded                     True                               7m37s
│ │             ├─InfrastructureReady                      True                               8m28s
│ │             ├─NodeHealthy                              True                               7m37s
│ │             └─SchedulerPodHealthy                      True                               8m
│ └─Machine/t-9z73sqxubetcjijh82-knvsh                     True                               3m52s
│               ├─APIServerPodHealthy                      True                               3m21s
│               ├─BootstrapReady                           True                               4m28s
│               ├─ControllerManagerPodHealthy              True                               2m12s
│               ├─EtcdMemberHealthy                        True                               3m21s
│               ├─EtcdPodHealthy                           True                               3m21s
│               ├─HealthCheckSucceeded                     True                               2m59s
│               ├─InfrastructureReady                      True                               3m52s
│               ├─NodeHealthy                              True                               2m59s
│               └─SchedulerPodHealthy                      True                               3m21s
└─Workers
  └─MachinePool/t-9z73sqxubetcjijh82-nodepool-0            True                               13m
                ├─BootstrapReady                           True                               13m
                ├─InfrastructureReady                      True                               21m
                └─ReplicasReady                            True                               27m
```

**Pull request merged**
