### PR TITLE
Specify JSON Schema draft

### PR DESCRIPTION
**Pull request by marians**
### What this PR does / why we need it

Towards https://github.com/giantswarm/roadmap/issues/2127

This PR changes the JSON Schema draft in `values.schema.json` from unspecified to the latest (2020-12).

### Checklist

- [ ] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/test create
/test upgrade

### CODE REVIEW

**Comment by marians** [comment]
@fiunchinho How can I find out what went wrong in the tests?

**Comment by fiunchinho** [comment]
> @fiunchinho How can I find out what went wrong in the tests?

Let me take a look. I don't think it's related to your change at all, so if this is blocking you, you can go ahead and merge it with admin permissions while I take a look at the tests.

**Review by fiunchinho — APPROVED** [review]

**Pull request merged**
