### PR TITLE
Release v1.1.0

### PR DESCRIPTION
**Pull request by taylorbot**

### CODE REVIEW

**Review by fiunchinho — APPROVED** [review]

**Review by Gacko — APPROVED** [review]

**Comment by fiunchinho** [comment]
China tests are still failing. Wasn't this the fix for that?

**Comment by paurosello** [comment]
> China tests are still failing. Wasn't this the fix for that?

running again, as I forgot to actually deploy the capa-iam-operator

**Comment by paurosello** [comment]
> China tests are still failing. Wasn't this the fix for that?

Ran the tests locally and I got green results:

```
E2E_RELEASE_VERSION="25.1.0" E2E_RELEASE_COMMIT="1d2de8c203e55e40ab63a4bae065d85635854b2b" E2E_KUBECONFIG=/tmp/galaxy-kubeconfig ginkgo --timeout 4h -v -r ./providers/capa/china/
.....
[AfterSuite] PASSED [627.537 seconds]
------------------------------

Ran 30 of 32 Specs in 2508.821 seconds
SUCCESS! -- 30 Passed | 0 Failed | 0 Pending | 2 Skipped
PASS

Ginkgo ran 1 suite in 42m3.128185375s
Test Suite Passed
```

**Pull request merged**
