### PR TITLE
Add global.metadata.labels to values schema

### PR DESCRIPTION
**Pull request by fiunchinho**
### What this PR does / why we need it

Towards https://github.com/giantswarm/giantswarm/issues/30901

### Checklist

- [X] Updated CHANGELOG.md.

### Trigger E2E tests

/run cluster-test-suites

### CODE REVIEW

**Review by Gacko — APPROVED** [review]

**Comment by Gacko** [comment]
Looks like a flake, huh?

**Comment by fiunchinho** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capa/china

**Comment by fiunchinho** [comment]
/run cluster-test-suites TARGET_SUITES=./providers/capa/china

**Pull request merged**
