### PR TITLE
Align files

### PR DESCRIPTION
**Pull request by architectbot**
This PR is generated by https://github.com/giantswarm/github, it will be merged automatically once all requirements are met

### CODE REVIEW

**Comment by marians** [comment]
@giantswarm/team-hydra I applied `schemalint normalize` using v2 in this branch to get the check green.

**Comment by fiunchinho** [comment]
@marians I'm not sure what do you mean. I think architect-bot may have overwritten your changes? I see the check is still red.

**Comment by marians** [comment]
@fiunchinho Not sure. The commit isn't there any more (or never has been?). Anyway, I did it again and I see the commit now and a green check.

**Review by fiunchinho — APPROVED** [review]

**Pull request merged**
