### PR TITLE
Use `gsoci.azurecr.io` registry

### PR DESCRIPTION
**Pull request by fiunchinho**
### What this PR does / why we need it
Towards https://github.com/giantswarm/roadmap/issues/3109

### Checklist

- [ ] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by calvix** [comment]
should we include also changes to the apps managed by helmRelease to also pull stuff from the the new registry?

**Comment by fiunchinho** [comment]
> should we include also changes to the apps managed by helmRelease to also pull stuff from the the new registry?

Yeah, I think that's a good idea.

**Comment by fiunchinho** [comment]
Using the changes on this PR and creating a new workload cluster without default apps I get no `docker.io` images

```
kubectl get pods --all-namespaces -o jsonpath="{.items[*].spec['initContainers', 'containers'][*].image}" |\
tr -s '[[:space:]]' '\n' |\
sort |\
uniq -c
      4 gsoci.azurecr.io/giantswarm/aws-ebs-csi-driver:v1.21.0
      3 gsoci.azurecr.io/giantswarm/aws-ebs-csi-volume-limiter:0.1.0
      2 gsoci.azurecr.io/giantswarm/cilium-operator-generic:v1.14.5
     42 gsoci.azurecr.io/giantswarm/cilium:v1.14.5
      3 gsoci.azurecr.io/giantswarm/coredns:1.11.1
      1 gsoci.azurecr.io/giantswarm/csi-attacher:v4.4.1
      3 gsoci.azurecr.io/giantswarm/csi-node-driver-registrar:v2.9.0
      1 gsoci.azurecr.io/giantswarm/csi-provisioner:v3.6.1
      1 gsoci.azurecr.io/giantswarm/csi-resizer:v1.8.1
      3 gsoci.azurecr.io/giantswarm/etcd:3.5.6-0
      1 gsoci.azurecr.io/giantswarm/hubble-relay:v1.14.5
      1 gsoci.azurecr.io/giantswarm/hubble-ui-backend:v0.12.1
      1 gsoci.azurecr.io/giantswarm/hubble-ui:v0.12.1
      3 gsoci.azurecr.io/giantswarm/kube-apiserver:v1.24.16
      3 gsoci.azurecr.io/giantswarm/kube-controller-manager:v1.24.16
      3 gsoci.azurecr.io/giantswarm/kube-scheduler:v1.24.16
      4 gsoci.azurecr.io/giantswarm/livenessprobe:v2.11.0
      3 quay.io/giantswarm/aws-cloud-controller-manager:v1.24.1
      2 quay.io/giantswarm/chart-operator:3.1.0
```

**Comment by fiunchinho** [comment]
With latest commit
```
3 gsoci.azurecr.io/giantswarm/aws-cloud-controller-manager:v1.25.14
      4 gsoci.azurecr.io/giantswarm/aws-ebs-csi-driver:v1.21.0
      3 gsoci.azurecr.io/giantswarm/aws-ebs-csi-volume-limiter:0.1.0
      2 gsoci.azurecr.io/giantswarm/cilium-operator-generic:v1.14.5
     42 gsoci.azurecr.io/giantswarm/cilium:v1.14.5
      3 gsoci.azurecr.io/giantswarm/coredns:1.11.1
      1 gsoci.azurecr.io/giantswarm/csi-attacher:v4.4.1
      3 gsoci.azurecr.io/giantswarm/csi-node-driver-registrar:v2.9.0
      1 gsoci.azurecr.io/giantswarm/csi-provisioner:v3.6.1
      1 gsoci.azurecr.io/giantswarm/csi-resizer:v1.8.1
      3 gsoci.azurecr.io/giantswarm/etcd:3.5.6-0
      1 gsoci.azurecr.io/giantswarm/hubble-relay:v1.14.5
      1 gsoci.azurecr.io/giantswarm/hubble-ui-backend:v0.12.1
      1 gsoci.azurecr.io/giantswarm/hubble-ui:v0.12.1
      3 gsoci.azurecr.io/giantswarm/kube-apiserver:v1.24.16
      3 gsoci.azurecr.io/giantswarm/kube-controller-manager:v1.24.16
      3 gsoci.azurecr.io/giantswarm/kube-scheduler:v1.24.16
      4 gsoci.azurecr.io/giantswarm/livenessprobe:v2.11.0
      2 quay.io/giantswarm/chart-operator:3.1.0
```

**Review by bdehri — APPROVED** [review]

**Pull request merged**
