### PR TITLE
bump cluster chart to 0.35.1

### PR DESCRIPTION
**Pull request by mnitchev**
### Checklist

- [x] Updated CHANGELOG.md.

### Trigger E2E tests

/run cluster-test-suites

### CODE REVIEW

**Comment by AndiDog** [comment]
> Let's not bump the `cluster` chart twice and rather include this in @AndiDog PR.

I'd rather put changes that belong together in separate PRs. As long as we're releasing cluster-aws together, is there an issue?

**Comment by Gacko** [comment]
Well, I assumed this change to be already tested if there has been a release of the `cluster` chart. So why not just bump the `cluster` chart in the `cluster-aws` only once? Your tests of the `cluster` chart already include the v0.35.1 version, right?

**Pull request closed without merging**
