### PR TITLE
Use 443 as default api-server Load Balancer port

### PR DESCRIPTION
**Pull request by mnitchev**
### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Review by fiunchinho — COMMENTED** [review]
What about calling it `apiServerLBPort` instead? I remember having trouble differentiating the two while investigating this issue.

**Comment by mnitchev** [comment]
Already had this discussion here https://github.com/giantswarm/cluster/pull/42#discussion_r1453599637
The value is already in the cluster chart

**Comment by fiunchinho** [comment]
I get that it's confusing within CAPI and CAPI providers (hence my first comment), but why keep using a potentially confusing field name when we could be more specific in our values?

**Comment by mnitchev** [comment]
Setting it to `apiServerLBPort` won't help with confusion IMO though. It makes sense in CAPA and in CAPZ with caveats, but in CAPI it has a different meaning and in other providers it might have none or something completely different. I guess the ideal thing here would be to have the value in the cluster chart be internal and named exactly as the thing that's being set as to remove ambiguity. So something like
```yaml
internal:
  clusterNetwork:
    apiServerPort: 6443
```

And then we have a separate value here that's named like the thing we _actually_ want to set and use a yaml anchor to configure the internal value like this:
```yaml
global:
  controlPlane:
    apiServerLoadBalancerPort: &lbPort 443
    ...
cluster:
  internal:
    clusterNetwork:
    apiServerPort: *lbPort
```
Not sure if that would work exactly though. But WDYT of the idea?

**Review by fiunchinho — APPROVED** [review]

**Pull request merged**
