### PR TITLE
Lookup region and AZs from management cluster

### PR DESCRIPTION
**Pull request by AverageMarcus**
* If the AWS region isn't set in the variables we'll attempt to pull it from the management cluster
* If the availability zones on a node pool aren't set we'll pull them from the management cluster

Towards: https://github.com/giantswarm/giantswarm/issues/21298

### CODE REVIEW

**Review by whites11 — APPROVED** [review]
dude, this is fucking smart!

**Comment by fiunchinho** [comment]
why do we want these to be optional values? I think it's normal to have to select region and AZs when creating a cluster.

I also find it weird to default the AZs to whatever we decided for the management cluster.

I'm not blocking this, anyway.

**Review by fiunchinho — APPROVED** [review]
I did not know this was possible, nice.

**Comment by AverageMarcus** [comment]
Why optional? - for region it makes sense as we (at least so far) have enforced WCs be created in the same region as the MC so is a bit pointless having to specify it every time you do `kubectl gs template cluster ....`

With the AZs, defaulting them to the same as the MC makes sense for most general cases (e.g. in eu-west-1 there's only 3 AZs to pick from so if the cluster is HA, which is is by default, then you'll always be selecting all three AZs) For the cases where different AZs are needed, those can still be provided (either on the template directly, or via a soon to be optional flag on `kubectl gs template`)

**Comment by AverageMarcus** [comment]
Related kubectl-gs change: https://github.com/giantswarm/kubectl-gs/pull/727

**Pull request merged**
