### PR TITLE
Test cluster chart PR #260

### PR DESCRIPTION
**Pull request by taylorbot**
> [!WARNING]
> DO NOT MERGE! This PR has been created automatically by @taylorbot on behalf of Nikola Prokopić (@nprokopic).

### Changes

Update the cluster chart version from `0.35.0` to `0.35.0-cc06b2331eb0c71139ac4eec1d743a2834fb3161` in order to test @nprokopic's cluster chart pull request https://github.com/giantswarm/cluster/pull/260.

Cluster chart pull request title: `Use MC Zot as registry mirror by default in all workload clusters`.

### Testing

Please comment this pull request with `/run cluster-test-suites` in order to run e2e tests.

### CODE REVIEW

**Comment by nprokopic** [comment]
updated PR here and debugging tests now

/run cluster-test-suites

**Comment by nprokopic** [comment]
Ah, the test is running against release 27.0.0, I don't think that will work.

**Comment by nprokopic** [comment]
Hmm, looks better than the previous run, let's see.

**Comment by AndiDog** [comment]
/run cluster-test-suites

to check if my latest CAPA changes, as currently deployed on the E2E MC, work fine.

**Comment by nprokopic** [comment]
> to check if my latest CAPA changes, as currently deployed on the E2E MC, work fine.

That was helpful, e2e tests are 💚 now 😄 Thanks 😄

**Pull request closed without merging**
