### PR TITLE
Disable cilium policies

### PR DESCRIPTION
**Pull request by whites11**
### What this PR does / why we need it

Towards: https://github.com/giantswarm/roadmap/issues/2860

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Review by calvix — APPROVED** [review]
lets go wild

**Review by AndiDog — CHANGES_REQUESTED** [review]
This will not remove anything. You need to revert https://github.com/giantswarm/cluster-aws/pull/387.

**Comment by AndiDog** [comment]
> This will not remove anything. You need to revert #387.

That is, add `remove: true` in addition to `enabled: true`

**Review by AndiDog — APPROVED** [review]

**Pull request merged**
