### PR TITLE
Add always-required values to `noProxy` list for aws-cloud-controller-manager-app and aws-ebs-csi-driver-app

### PR DESCRIPTION
**Pull request by AndiDog**
### What this PR does / why we need it

This used to work without users having to provide these values explicitly. Even if the `noProxy` config is empty, the defaults should lead to a working cluster. The PR fixes this again after `HelmRelease`s were introduced.

Somewhat related to testing of https://github.com/giantswarm/giantswarm/issues/27266

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/test upgrade

/run cluster-test-suites

### CODE REVIEW

**Comment by fiunchinho** [comment]
Probably worth adding it here too
- https://github.com/giantswarm/cluster-aws/blob/3617cae8520bd74c69f99e91f27d88f4d94672be/helm/cluster-aws/templates/_helpers.tpl#L92
- https://github.com/giantswarm/cluster-aws/blob/3617cae8520bd74c69f99e91f27d88f4d94672be/helm/cluster-aws/files/http-proxy.conf#L4

**Comment by AndiDog** [comment]
@fiunchinho I made it consistent by using a central template `include`

**Comment by AndiDog** [comment]
/run cluster-test-suites

Checking why `kube-system/aws-pod-identity-webhook-app` pod remained pending in the test.

**Pull request merged**
