### PR TITLE
Move extraPolicies from cilium to network-policies-app

### PR DESCRIPTION
**Pull request by mcharriere**
### What this PR does / why we need it

- disables and removes the `extraPolicies` network policies from `cilium`
- enables the `extraPolicies` network policies in the `network-policies` app

Towards https://github.com/giantswarm/roadmap/issues/3261

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by mcharriere** [comment]
cert manager is failing to generate the cert 
```
E0321 20:13:22.013981       1 controller.go:167] "cert-manager/challenges: re-queuing item due to error processing" err="failed to determine Route 53 hosted zone ID: zone  not found in Route 53 for domain _acme-challenge.hello.cluster.provider.gigantic.io." key="giantswarm/hello-world-tls-1-2484205327-3464862705"
```

**Comment by Gacko** [comment]
Is this PR still required or was this just for testing something on `cluster` chart? If no, please do not forget to also delete the branch when closing the PR. Thank you! :)

**Comment by mcharriere** [comment]
it's needed. Waiting on `cluster` chart release.

**Comment by Gacko** [comment]
Approved it! :)

**Comment by mcharriere** [comment]
@giantswarm/team-cabbage @giantswarm/team-phoenix I'd appreciate a review here. thank you :)

**Review by ubergesundheit — APPROVED** [review]
LGTM

**Review by kopiczko — APPROVED** [review]

**Pull request merged**
