### PR TITLE
fix-subnet-filter-for-az

### PR DESCRIPTION
**Pull request by calvix**
towards https://github.com/giantswarm/giantswarm/issues/29201

/run cluster-test-suites

### CODE REVIEW

**Comment by calvix** [comment]
the fix seems to be easy but we might need to manually  fix MCs before updating to this version as they might run instances in the wrong subnets

**Comment by calvix** [comment]
ASG automatically balances instances and removes the ones from the wrong AZs, which is neat.

**Review by fiunchinho — APPROVED** [review]

**Pull request merged**
