### PR TITLE
Tolerate CAPI taints on uninitialized nodes

### PR DESCRIPTION
**Pull request by fiunchinho**
### What this PR does / why we need it

`cilium` helm release takes very long to become ready because cilium ui and cilium relay pods can't be scheduled on CAPI uninitialized nodes. I think it's safe to add these tolerations, because CAPI initialization of nodes is just syncing labels.

### Checklist

- [X] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Review by calvix — APPROVED** [review]
would it be useful for all helmRelease based apps?

**Comment by fiunchinho** [comment]
> would it be useful for all helmRelease based apps?

I didn't find it to be an issue for any of the others, so to keep things simple, I'd keep it only for cilium for now.

**Pull request merged**
