### PR TITLE
Replace IPV4_LOCAL with COREOS_IPV4_LOCAL value from coreos-metadata service

### PR DESCRIPTION
**Pull request by njuettner**
### What this PR does / why we need it

In order to support all providers we replaced existing `COREOS_EC2_IPV4_LOCAL` and `COREOS_EC2_HOSTNAME` in `cluster` chart and add a support to use environment variables.

Nothing will change for CAPA and it will work the same as before.

### Checklist

- [x] Updated CHANGELOG.md.

### Trigger E2E tests

/run cluster-test-suites

### CODE REVIEW

**Review by calvix — APPROVED** [review]
LGTM, just to confirm my understanding, each chart has customer values for the ENV and we set it via the providerIntegration values?

**Review by Gacko — APPROVED** [review]
LGTM, do not forget to reset the `Chart.yaml` & `Chart.lock`. 😉

**Comment by njuettner** [comment]
> LGTM, just to confirm my understanding, each chart has customer values for the ENV and we set it via the providerIntegration values?

Correct

**Comment by njuettner** [comment]
Tests were green except `Cilium ENI mode tests scale [It] scales node by creating anti-affinity pods` it was due to spot instances not being available.

We have the same test for CAPA Standard and this was working fine. I'll merge this PR


https://tekton.ci.giantswarm.io/#/namespaces/tekton-pipelines/pipelineruns/pr-cluster-aws-627-cluster-test-suitesmmh5w?pipelineTask=run-tests&taskRunName=pr-cluster-aws-627-cluster-test-suitesmmh5w-run-tests-3&step=run-tests

**Pull request merged**
