### PR TITLE
remove-bastion

### PR DESCRIPTION
**Pull request by calvix**
towards https://github.com/giantswarm/giantswarm/issues/29254

/run cluster-test-suites

### CODE REVIEW

**Comment by calvix** [comment]
the test fails because of test for bastion so it needs to be first disabled for CAPA - https://github.com/giantswarm/cluster-test-suites/pull/164

**Review by fiunchinho — CHANGES_REQUESTED** [review]
Please update the changelog.

**Review by fiunchinho — APPROVED** [review]

**Pull request merged**
